### PR TITLE
fix: issue #134

### PR DESCRIPTION
**Pull request by ryomahan**
fix issue #134 without broken code

### Tips for the one 
I create a selfuse version package named [ryomahan-vite-plugin-html](https://www.npmjs.com/package/ryomahan-vite-plugin-html), if you really need it you can install by `npm install ryomahan-vite-plugin-html`, srouce code in [ryomahan/vite-plugin-html](https://github.com/ryomahan/vite-plugin-html)

### CODE REVIEW

**Comment by oinochoe** [comment]
@ryomahan I installed version 3.2.1 but I am still getting the following error:
```
WARN  plugin 'vite:html' uses deprecated 'enforce' option. Use 'order' option instead.                
WARN  plugin 'vite:html' uses deprecated 'transform' option. Use 'handler' option instead.
```

Do you know the reason?

**Comment by ryomahan** [comment]
> @ryomahan I installed version 3.2.1 but I am still getting the following error:
> 
> ```
> WARN  plugin 'vite:html' uses deprecated 'enforce' option. Use 'order' option instead.                
> WARN  plugin 'vite:html' uses deprecated 'transform' option. Use 'handler' option instead.
> ```
> 
> Do you know the reason? 😢

owner don't release new version, so you need add viteNext: true in this plugin's config

**Comment by oinochoe** [comment]
@ryomahan Thanks, I solved via `viteNext` option.
What I'm curious about is that the method seems to simply handle exceptions with an if statement, so I wonder if it is a permanent method. Would it be a good option if another version is created in the future?

**Comment by ryomahan** [comment]
@oinochoe  You can see #134 and #140 

 #134 We discussed this issue at length

 #140  I solved the problem with tips from  #134

**Pull request merged**
